# Generated by Django 5.2.10 on 2026-09-19 14:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_grupbahan_boleh_dijual_retail'),
        ('master', '0004_hargajual'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('nomor_so', models.CharField(blank=True, max_length=50, unique=True)),
                ('tanggal', models.DateField()),
                ('catatan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DISETUJUI', 'Disetujui'), ('SELESAI', 'Selesai'), ('BATAL', 'Batal')], db_index=True, default='DRAFT', max_length=15)),
                ('ppn_persen', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('ppn_nominal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('entitas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='core.entitas')),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='master.pelanggan')),
            ],
            options={
                'verbose_name_plural': 'Sales Order',
                'db_table': 'tx_sales_order',
                'ordering': ['-tanggal', '-nomor_so'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('harga_jual', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='so_items', to='master.produk')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales_order.salesorder')),
            ],
            options={
                'verbose_name_plural': 'Sales Order Items',
                'db_table': 'tx_sales_order_item',
                'ordering': ['id'],
            },
        ),
    ]
