# Generated by Django 5.2.10 on 2026-09-19 03:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0003_seed_master_produk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriAkun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, unique=True)),
                ('tipe_saldo', models.CharField(choices=[('DEBIT', 'DEBIT'), ('KREDIT', 'KREDIT')], max_length=10)),
            ],
            options={
                'db_table': 'retail_kategori_akun',
            },
        ),
        migrations.CreateModel(
            name='CabangToko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(blank=True, max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabang_toko', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cabang Toko',
                'verbose_name_plural': 'Cabang Toko',
                'db_table': 'retail_cabang_toko',
            },
        ),
        migrations.CreateModel(
            name='BukuHutangRetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referensi', models.CharField(max_length=100)),
                ('tanggal_hutang', models.DateField(default=django.utils.timezone.now)),
                ('jatuh_tempo', models.DateField(blank=True, null=True)),
                ('keterangan', models.TextField(blank=True)),
                ('total_hutang', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_dibayar', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('BELUM LUNAS', 'BELUM LUNAS'), ('MENCICIL', 'MENCICIL'), ('LUNAS', 'LUNAS')], default='BELUM LUNAS', max_length=20)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('cabang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daftar_hutang', to='retail.cabangtoko')),
            ],
            options={
                'db_table': 'retail_buku_hutang',
                'ordering': ['-tanggal_hutang', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AkunBukuBesar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('aktif', models.BooleanField(default=True)),
                ('cabang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='retail.cabangtoko')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='retail.kategoriakun')),
            ],
            options={
                'db_table': 'retail_akun_buku_besar',
            },
        ),
        migrations.CreateModel(
            name='PelangganRetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nomor_telepon', models.CharField(blank=True, max_length=20, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('limit_piutang', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('default_tempo_hari', models.IntegerField(default=30)),
                ('cabang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pelanggan', to='retail.cabangtoko')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'retail_pelanggan',
            },
        ),
        migrations.CreateModel(
            name='BukuPiutangRetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_piutang', models.DateField(default=django.utils.timezone.now)),
                ('jatuh_tempo', models.DateField()),
                ('total_piutang', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_dibayar', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('BELUM LUNAS', 'BELUM LUNAS'), ('MENCICIL', 'MENCICIL'), ('LUNAS', 'LUNAS')], default='BELUM LUNAS', max_length=20)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buku_piutang', to='retail.pelangganretail')),
            ],
            options={
                'db_table': 'retail_buku_piutang',
                'ordering': ['-tanggal_piutang', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PenerimaanBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_penerimaan', models.CharField(max_length=50, unique=True)),
                ('referensi_logistik', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_kirim', models.DateTimeField(blank=True, null=True)),
                ('tanggal_terima', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DIKIRIM', 'DIKIRIM'), ('DITERIMA SEBAGIAN', 'DITERIMA SEBAGIAN'), ('SELESAI', 'SELESAI')], default='DIKIRIM', max_length=20)),
                ('keterangan', models.TextField(blank=True)),
                ('cabang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_penerimaan', to='retail.cabangtoko')),
            ],
            options={
                'db_table': 'retail_penerimaan_barang',
                'ordering': ['-tanggal_terima'],
            },
        ),
        migrations.CreateModel(
            name='ItemPenerimaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kemasan', models.CharField(max_length=50)),
                ('unit_dikirim', models.IntegerField(default=0)),
                ('unit_diterima', models.IntegerField(default=0)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.masterproduk')),
                ('penerimaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='retail.penerimaanbarang')),
            ],
            options={
                'db_table': 'retail_item_penerimaan',
            },
        ),
        migrations.CreateModel(
            name='RiwayatBayarHutang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_bayar', models.DateField(default=django.utils.timezone.now)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('metode_bayar', models.CharField(max_length=50)),
                ('catatan', models.CharField(blank=True, max_length=255)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('hutang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_bayar', to='retail.bukuhutangretail')),
            ],
            options={
                'db_table': 'retail_riwayat_bayar_hutang',
            },
        ),
        migrations.CreateModel(
            name='RiwayatBayarPiutang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_bayar', models.DateField(default=django.utils.timezone.now)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('metode_bayar', models.CharField(max_length=50)),
                ('catatan', models.CharField(blank=True, max_length=255)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('piutang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_bayar', to='retail.bukupiutangretail')),
            ],
            options={
                'db_table': 'retail_riwayat_bayar_piutang',
            },
        ),
        migrations.CreateModel(
            name='SalesRetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('persentase_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('aktif', models.BooleanField(default=True)),
                ('cabang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='retail.cabangtoko')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'retail_sales',
            },
        ),
        migrations.AddField(
            model_name='pelangganretail',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='retail.salesretail'),
        ),
        migrations.CreateModel(
            name='SelisihStok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kemasan', models.CharField(max_length=50)),
                ('waktu_lapor', models.DateTimeField(auto_now_add=True)),
                ('stok_sistem', models.IntegerField()),
                ('stok_aktual', models.IntegerField()),
                ('selisih', models.IntegerField()),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('DISETUJUI', 'DISETUJUI'), ('DITOLAK', 'DITOLAK')], default='PENDING', max_length=20)),
                ('cabang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.cabangtoko')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.produk')),
            ],
            options={
                'db_table': 'retail_selisih_stok',
            },
        ),
        migrations.CreateModel(
            name='SesiKasir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_buka', models.DateTimeField(auto_now_add=True)),
                ('waktu_tutup', models.DateTimeField(blank=True, null=True)),
                ('saldo_awal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_penjualan', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('AKTIF', 'AKTIF'), ('DITUTUP', 'DITUTUP')], default='AKTIF', max_length=20)),
                ('cabang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.cabangtoko')),
                ('kasir', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'retail_sesi_kasir',
                'ordering': ['-waktu_buka'],
            },
        ),
        migrations.CreateModel(
            name='SelisihKasir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_lapor', models.DateTimeField(auto_now_add=True)),
                ('saldo_sistem', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_aktual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('selisih', models.DecimalField(decimal_places=2, max_digits=12)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('diselesaikan', models.BooleanField(default=False)),
                ('sesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_selisih', to='retail.sesikasir')),
            ],
            options={
                'db_table': 'retail_selisih_kasir',
            },
        ),
        migrations.CreateModel(
            name='StokRetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kemasan', models.CharField(default='PCS', max_length=50)),
                ('total_unit', models.IntegerField(default=0)),
                ('harga_jual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cabang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stok', to='retail.cabangtoko')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.masterproduk')),
            ],
            options={
                'db_table': 'retail_stok',
                'unique_together': {('cabang', 'produk', 'kemasan')},
            },
        ),
        migrations.CreateModel(
            name='MutasiStokRetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('jenis', models.CharField(choices=[('PENERIMAAN', 'Penerimaan Barang (Inbound)'), ('PENJUALAN', 'Penjualan Kasir (Outbound)'), ('RETUR', 'Retur Penjualan (Inbound)'), ('PENYESUAIAN', 'Penyesuaian Stok / Opname')], max_length=20)),
                ('referensi', models.CharField(max_length=100)),
                ('unit_masuk', models.IntegerField(default=0)),
                ('unit_keluar', models.IntegerField(default=0)),
                ('saldo_akhir', models.IntegerField(default=0)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('stok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_mutasi', to='retail.stokretail')),
            ],
            options={
                'db_table': 'retail_mutasi_stok',
                'ordering': ['-tanggal', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TransaksiJurnal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_jurnal', models.CharField(max_length=50, unique=True)),
                ('tanggal', models.DateTimeField(default=django.utils.timezone.now)),
                ('referensi', models.CharField(max_length=100)),
                ('keterangan', models.TextField()),
                ('cabang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.cabangtoko')),
            ],
            options={
                'db_table': 'retail_transaksi_jurnal',
                'ordering': ['-tanggal', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DetailJurnal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('kredit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='retail.akunbukubesar')),
                ('jurnal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_jurnal', to='retail.transaksijurnal')),
            ],
            options={
                'db_table': 'retail_detail_jurnal',
            },
        ),
        migrations.CreateModel(
            name='TransaksiPOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_struk', models.CharField(max_length=50, unique=True)),
                ('waktu_transaksi', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pajak', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metode_bayar', models.CharField(choices=[('TUNAI', 'TUNAI'), ('QRIS', 'QRIS'), ('TRANSFER', 'TRANSFER'), ('TEMPO', 'TEMPO')], max_length=20)),
                ('status', models.CharField(choices=[('BERHASIL', 'BERHASIL'), ('RETUR', 'RETUR')], default='BERHASIL', max_length=20)),
                ('pelanggan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='retail.pelangganretail')),
                ('sales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='retail.salesretail')),
                ('sesi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaksi', to='retail.sesikasir')),
            ],
            options={
                'db_table': 'retail_transaksi_pos',
                'ordering': ['-waktu_transaksi'],
            },
        ),
        migrations.CreateModel(
            name='ItemTransaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kemasan', models.CharField(max_length=50)),
                ('qty_unit', models.IntegerField(default=1)),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.masterproduk')),
                ('transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='retail.transaksipos')),
            ],
            options={
                'db_table': 'retail_item_transaksi',
            },
        ),
        migrations.AddField(
            model_name='bukupiutangretail',
            name='transaksi',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='retail.transaksipos'),
        ),
        migrations.CreateModel(
            name='BonusSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('nominal_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus', to='retail.salesretail')),
                ('transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.transaksipos')),
            ],
            options={
                'db_table': 'retail_bonus_sales',
            },
        ),
    ]
