# Generated by Django 5.2.10 on 2026-09-19 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cabangtoko'),
        ('master', '0003_seed_master_produk'),
        ('retail', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stokretail',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='itempenerimaan',
            name='entitas',
            field=models.ForeignKey(blank=True, help_text='Pemilik barang, dibawa dari ItemDistribusi.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_penerimaan_retail', to='core.entitas'),
        ),
        migrations.AddField(
            model_name='stokretail',
            name='entitas',
            field=models.ForeignKey(blank=True, help_text='Pemilik barang. Kosong untuk data lama sebelum kolom ini ada.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stok_retail', to='core.entitas'),
        ),
        migrations.AlterUniqueTogether(
            name='stokretail',
            unique_together={('cabang', 'produk', 'kemasan', 'entitas')},
        ),
    ]
