# Generated by Django 5.2.10 on 2026-09-16 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('akunting', '0003_initial'),
        ('core', '0003_cabangtoko'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nama', models.CharField(max_length=150)),
                ('tahun', models.PositiveSmallIntegerField()),
                ('basis_periode', models.CharField(choices=[('BULANAN', 'Bulanan'), ('TAHUNAN', 'Tahunan')], default='BULANAN', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('AKTIF', 'Aktif'), ('DITUTUP', 'Ditutup'), ('BATAL', 'Batal')], db_index=True, default='DRAFT', max_length=10)),
                ('versi', models.PositiveIntegerField(default=1)),
                ('keterangan', models.TextField(blank=True)),
                ('dibuat_oleh', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entitas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='core.entitas')),
            ],
            options={
                'verbose_name_plural': 'Budget',
                'db_table': 'finance_budget',
                'ordering': ['-tahun', 'nama', '-versi'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bulan', models.PositiveSmallIntegerField(help_text='0 = seluruh tahun (basis TAHUNAN); 1–12 = bulan spesifik.')),
                ('nominal_anggaran', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('keterangan', models.TextField(blank=True)),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='akunting.akun')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.budget')),
                ('dibuat_oleh', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Budget line',
                'db_table': 'finance_budget_line',
                'ordering': ['budget', 'bulan', 'akun'],
            },
        ),
        migrations.CreateModel(
            name='COGSTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tahun', models.PositiveSmallIntegerField()),
                ('bulan', models.PositiveSmallIntegerField()),
                ('nominal_target', models.DecimalField(decimal_places=2, max_digits=18)),
                ('akun_cogs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cogs_targets', to='akunting.akun')),
                ('dibuat_oleh', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entitas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cogs_targets', to='core.entitas')),
            ],
            options={
                'verbose_name_plural': 'COGS target',
                'db_table': 'finance_cogs_target',
                'ordering': ['-tahun', '-bulan'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FixedCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nama', models.CharField(max_length=150)),
                ('nominal_bulanan', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField(blank=True, null=True)),
                ('aktif', models.BooleanField(db_index=True, default=True)),
                ('auto_masuk_budget', models.BooleanField(default=False, help_text='Hanya memengaruhi baseline budget/planning. Tidak pernah membuat expense actual.')),
                ('keterangan', models.TextField(blank=True)),
                ('akun_beban', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_costs', to='akunting.akun')),
                ('dibuat_oleh', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entitas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_costs', to='core.entitas')),
            ],
            options={
                'verbose_name_plural': 'Fixed cost',
                'db_table': 'finance_fixed_cost',
                'ordering': ['-tanggal_mulai', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('forecast_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('forecast_cogs', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('forecast_opex', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('forecast_other_income', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('forecast_other_expense', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('catatan', models.TextField(blank=True)),
                ('dibuat_oleh', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecasts', to='core.periodeakuntansi')),
            ],
            options={
                'verbose_name_plural': 'Forecast',
                'db_table': 'finance_forecast',
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='RevenueTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tahun', models.PositiveSmallIntegerField()),
                ('bulan', models.PositiveSmallIntegerField()),
                ('nominal_target', models.DecimalField(decimal_places=2, max_digits=18)),
                ('akun_pendapatan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_targets', to='akunting.akun')),
                ('dibuat_oleh', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entitas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_targets', to='core.entitas')),
            ],
            options={
                'verbose_name_plural': 'Revenue target',
                'db_table': 'finance_revenue_target',
                'ordering': ['-tahun', '-bulan'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('entitas', 'nama', 'tahun', 'versi'), name='uq_budget_entitas_nama_tahun_versi'),
        ),
        migrations.AddIndex(
            model_name='budgetline',
            index=models.Index(fields=['budget', 'akun'], name='ix_budgetline_budget_akun'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.UniqueConstraint(fields=('budget', 'akun', 'bulan'), name='uq_budgetline_budget_akun_bulan'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.CheckConstraint(condition=models.Q(('bulan__gte', 0), ('bulan__lte', 12)), name='ck_budgetline_bulan_valid'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.CheckConstraint(condition=models.Q(('nominal_anggaran__gte', 0)), name='ck_budgetline_nominal_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='cogstarget',
            constraint=models.UniqueConstraint(fields=('entitas', 'akun_cogs', 'tahun', 'bulan'), name='uq_cogstarget_entitas_akun_tahun_bulan'),
        ),
        migrations.AddConstraint(
            model_name='cogstarget',
            constraint=models.CheckConstraint(condition=models.Q(('bulan__gte', 1), ('bulan__lte', 12)), name='ck_cogstarget_bulan_valid'),
        ),
        migrations.AddIndex(
            model_name='fixedcost',
            index=models.Index(fields=['aktif', 'tanggal_mulai', 'tanggal_selesai'], name='ix_fixedcost_periode_aktif'),
        ),
        migrations.AddConstraint(
            model_name='fixedcost',
            constraint=models.CheckConstraint(condition=models.Q(('nominal_bulanan__gte', 0)), name='ck_fixedcost_nominal_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='fixedcost',
            constraint=models.CheckConstraint(condition=models.Q(('tanggal_selesai__isnull', True), ('tanggal_selesai__gte', models.F('tanggal_mulai')), _connector='OR'), name='ck_fixedcost_tanggal_valid'),
        ),
        migrations.AddIndex(
            model_name='forecast',
            index=models.Index(fields=['periode', '-dibuat_pada'], name='ix_forecast_terbaru'),
        ),
        migrations.AddConstraint(
            model_name='revenuetarget',
            constraint=models.UniqueConstraint(fields=('entitas', 'akun_pendapatan', 'tahun', 'bulan'), name='uq_revenuetarget_entitas_akun_tahun_bulan'),
        ),
        migrations.AddConstraint(
            model_name='revenuetarget',
            constraint=models.CheckConstraint(condition=models.Q(('bulan__gte', 1), ('bulan__lte', 12)), name='ck_revenuetarget_bulan_valid'),
        ),
    ]
