# Generated by Django 5.2.10 on 2026-09-17 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cabangtoko'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RekapPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tahun', models.PositiveSmallIntegerField()),
                ('bulan', models.PositiveSmallIntegerField()),
                ('jumlah_po', models.PositiveIntegerField(default=0)),
                ('jumlah_item', models.PositiveIntegerField(default=0)),
                ('nilai_pesan', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('nilai_diterima', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('nilai_ppn', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('dihitung_pada', models.DateTimeField(auto_now=True)),
                ('dibekukan', models.BooleanField(db_index=True, default=False)),
                ('dibuat_oleh', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entitas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rekap_po', to='core.entitas')),
            ],
            options={
                'verbose_name': 'Rekap purchase order',
                'verbose_name_plural': 'Rekap purchase order',
                'db_table': 'finance_rekap_purchase_order',
                'ordering': ['-tahun', '-bulan', 'entitas'],
                'indexes': [models.Index(fields=['tahun', 'bulan'], name='ix_rekap_po_periode')],
                'constraints': [models.UniqueConstraint(fields=('entitas', 'tahun', 'bulan'), name='uq_rekap_po_entitas_tahun_bulan'), models.CheckConstraint(condition=models.Q(('bulan__gte', 1), ('bulan__lte', 12)), name='ck_rekap_po_bulan_valid')],
            },
        ),
    ]
