# Generated by Django 5.2.10 on 2026-09-17 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cabangtoko'),
        ('finance', '0002_rekappurchaseorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RekapMutasiKlaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tahun', models.PositiveSmallIntegerField()),
                ('bulan', models.PositiveSmallIntegerField()),
                ('jumlah_mutasi', models.PositiveIntegerField(default=0)),
                ('qty_setor', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('nilai_setor', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('qty_tarik', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('nilai_tarik', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('saldo_akhir', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('qty_setor_kumulatif', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('qty_tarik_kumulatif', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('dihitung_pada', models.DateTimeField(auto_now=True)),
                ('dibekukan', models.BooleanField(db_index=True, default=False)),
                ('dibuat_oleh', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entitas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rekap_klaim', to='core.entitas')),
            ],
            options={
                'verbose_name': 'Rekap mutasi klaim',
                'verbose_name_plural': 'Rekap mutasi klaim',
                'db_table': 'finance_rekap_mutasi_klaim',
                'ordering': ['-tahun', '-bulan', 'entitas'],
                'indexes': [models.Index(fields=['tahun', 'bulan'], name='ix_rekap_klaim_periode')],
                'constraints': [models.UniqueConstraint(fields=('entitas', 'tahun', 'bulan'), name='uq_rekap_klaim_entitas_tahun_bulan'), models.CheckConstraint(condition=models.Q(('bulan__gte', 1), ('bulan__lte', 12)), name='ck_rekap_klaim_bulan_valid')],
            },
        ),
        migrations.CreateModel(
            name='RekapMutasiProduksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tahun', models.PositiveSmallIntegerField()),
                ('bulan', models.PositiveSmallIntegerField()),
                ('batch_mixing', models.PositiveIntegerField(default=0)),
                ('batch_blending', models.PositiveIntegerField(default=0)),
                ('qty_hasil', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('nilai_hasil', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('qty_susut', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('nilai_susut', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('qty_packing', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('nilai_packing', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('wip_akhir_kg', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('wip_akhir_nilai', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('pool_akhir_nilai', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('pool_kemasan_akhir_nilai', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('dihitung_pada', models.DateTimeField(auto_now=True)),
                ('dibekukan', models.BooleanField(db_index=True, default=False)),
                ('dibuat_oleh', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rekap mutasi produksi',
                'verbose_name_plural': 'Rekap mutasi produksi',
                'db_table': 'finance_rekap_mutasi_produksi',
                'ordering': ['-tahun', '-bulan'],
                'constraints': [models.UniqueConstraint(fields=('tahun', 'bulan'), name='uq_rekap_produksi_tahun_bulan'), models.CheckConstraint(condition=models.Q(('bulan__gte', 1), ('bulan__lte', 12)), name='ck_rekap_produksi_bulan_valid')],
            },
        ),
    ]
