# Generated by Django 5.2.10 on 2026-09-14 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0003_seed_master_produk'),
    ]

    operations = [
        migrations.CreateModel(
            name='StikerBesar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_file', models.CharField(max_length=100, unique=True)),
                ('file_template', models.FileField(upload_to='templates/stiker_besar/')),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Template Stiker Besar',
                'verbose_name_plural': 'Template Stiker Besar',
                'ordering': ['nama_file'],
            },
        ),
        migrations.CreateModel(
            name='StikerKecil12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_file', models.CharField(max_length=100, unique=True)),
                ('file_template', models.FileField(upload_to='templates/stiker_kecil_12/')),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Template Stiker Kecil (12 Slot)',
                'verbose_name_plural': 'Template Stiker Kecil (12 Slot)',
                'ordering': ['nama_file'],
            },
        ),
        migrations.CreateModel(
            name='GenerateStikerBesar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_unit', models.PositiveIntegerField(default=0)),
                ('pola_terdeteksi', models.CharField(blank=True, max_length=10, null=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('file_hasil', models.CharField(blank=True, max_length=255, null=True)),
                ('alamat_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitur.stikerbesar')),
            ],
            options={
                'verbose_name': 'Generate Stiker Besar',
                'verbose_name_plural': 'Generate Stiker Besar',
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='GenerateStikerKecil12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_unit', models.PositiveIntegerField(default=0)),
                ('pola_terdeteksi', models.CharField(blank=True, max_length=15, null=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('file_hasil', models.CharField(blank=True, max_length=255, null=True)),
                ('alamat_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitur.stikerkecil12')),
            ],
            options={
                'verbose_name': 'Generate Stiker Kecil (12 Slot)',
                'verbose_name_plural': 'Generate Stiker Kecil (12 Slot)',
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='ItemCetak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grup', models.CharField(help_text="Posisi dalam pola, mis. huruf 'A' pada AABB — bukan tipe barang.", max_length=1, verbose_name='Grup Pola')),
                ('tipe', models.CharField(help_text='Klasifikasi barang, independen dari grup pola.', max_length=100, verbose_name='Tipe Barang')),
                ('lot', models.DateField(verbose_name='Tanggal Lot')),
                ('net', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Net (KGS)')),
                ('generate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_set', to='fitur.generatestikerbesar')),
                ('nama_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing_hasil_besar', to='master.masterproduk')),
            ],
            options={
                'verbose_name': 'Item Cetak',
                'verbose_name_plural': 'Item Cetak',
                'ordering': ['grup'],
                'unique_together': {('generate', 'grup')},
            },
        ),
        migrations.CreateModel(
            name='ItemCetakKecil12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grup', models.CharField(help_text="Posisi dalam pola, mis. huruf 'A' pada AABBCC... — bukan tipe barang.", max_length=1, verbose_name='Grup Pola')),
                ('nama_item', models.CharField(max_length=255, verbose_name='Nama Barang')),
                ('tipe', models.CharField(help_text='Klasifikasi barang, independen dari grup pola.', max_length=100, verbose_name='Tipe Barang')),
                ('lot', models.DateField(verbose_name='Tanggal Lot')),
                ('net', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Net (KGS)')),
                ('generate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_set', to='fitur.generatestikerkecil12')),
            ],
            options={
                'verbose_name': 'Item Cetak Kecil (12 Slot)',
                'verbose_name_plural': 'Item Cetak Kecil (12 Slot)',
                'ordering': ['grup'],
                'unique_together': {('generate', 'grup')},
            },
        ),
    ]
