# Generated by Django 5.2.10 on 2026-09-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitur', '0002_ubah_nama_item_jadi_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcetakkecil12',
            name='nama_item',
            field=models.CharField(max_length=255, verbose_name='Nama Barang'),
        ),
    ]
