# Generated by Django 5.2.10 on 2026-09-19 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitur', '0005_itemcetakkecil12_nama_item_jadi_fk'),
        ('master', '0003_seed_master_produk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcetakkecil12',
            name='nama_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packing_hasil_kecil12', to='master.masterproduk'),
        ),
    ]
