# Generated by Django 5.2.10 on 2026-09-07 04:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tangki',
            name='saldo_kg',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='tangki',
            name='saldo_nilai',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
    ]
