# Generated by Django 5.2.10 on 2026-09-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cabangtoko'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupbahan',
            name='boleh_dijual_retail',
            field=models.BooleanField(default=True, help_text='Kalau False, stok milik grup ini tidak muncul di kasir cabang.'),
        ),
    ]
