# Generated by Django 5.2.10 on 2026-09-19 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_seed_master_produk'),
    ]

    operations = [
        migrations.CreateModel(
            name='HargaJual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('kemasan', models.CharField(max_length=50)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=12)),
                ('aktif', models.BooleanField(default=True)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harga_jual', to='master.masterproduk')),
            ],
            options={
                'verbose_name_plural': 'Harga jual',
                'db_table': 'master_harga_jual',
                'ordering': ['produk', 'kemasan'],
                'constraints': [models.UniqueConstraint(fields=('produk', 'kemasan'), name='uq_harga_jual_produk_kemasan')],
            },
        ),
    ]
