server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /retail {
        alias /usr/share/nginx/html/retail;
        
        try_files $uri $uri/ /retail/index.html;
    }

    location / {
        return 404; 
    }
}