# Generated by Django 5.2.10 on 2026-09-07 04:05

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('inventory', '0002_initial'),
        ('master', '0001_initial'),
        ('produksi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StokBarangJadi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('qty_unit', models.IntegerField(default=0)),
                ('qty_kg', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
            ],
            options={
                'verbose_name_plural': 'Stok Barang Jadi',
                'db_table': 'inventory_stok_barang_jadi',
            },
        ),
        migrations.CreateModel(
            name='StokItemsPabrik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('qty_kg', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
            ],
            options={
                'verbose_name_plural': 'Stok Items Pabrik',
                'db_table': 'inventory_stok_items_pabrik',
            },
        ),
        migrations.RemoveIndex(
            model_name='packing',
            name='ix_pack_batch',
        ),
        migrations.RemoveIndex(
            model_name='packing',
            name='ix_pack_hasil',
        ),
        migrations.AddField(
            model_name='packing',
            name='kemasan_dalam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packing_dalam', to='inventory.poolkemasan'),
        ),
        migrations.AddField(
            model_name='packing',
            name='qty_kemasan_dalam',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='packing',
            name='kemasan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing_luar', to='inventory.poolkemasan'),
        ),
        migrations.AlterField(
            model_name='packing',
            name='posted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='packing',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Diposting'), ('VOID', 'Dibatalkan')], default='DRAFT', max_length=10),
        ),
        migrations.AddIndex(
            model_name='packing',
            index=models.Index(fields=['batch'], name='ix_pack_batch_baru'),
        ),
        migrations.AddIndex(
            model_name='packing',
            index=models.Index(fields=['nama_hasil'], name='ix_pack_hasil_baru'),
        ),
        migrations.AddField(
            model_name='stokbarangjadi',
            name='entitas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stok_barang_jadi', to='core.entitas'),
        ),
        migrations.AddField(
            model_name='stokbarangjadi',
            name='grup_bahan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stok_barang_jadi', to='core.grupbahan'),
        ),
        migrations.AddField(
            model_name='stokbarangjadi',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stok_barang_jadi', to='master.masterproduk'),
        ),
        migrations.AddField(
            model_name='stokbarangjadi',
            name='kemasan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stok_barang_jadi', to='inventory.kemasan'),
        ),
        migrations.AddField(
            model_name='stokitemspabrik',
            name='entitas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stok_items_pabrik', to='core.entitas'),
        ),
        migrations.AddField(
            model_name='stokitemspabrik',
            name='grup_bahan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stok_items_pabrik', to='core.grupbahan'),
        ),
        migrations.AddField(
            model_name='stokitemspabrik',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stok_items_pabrik', to='master.masterproduk'),
        ),
        migrations.AddConstraint(
            model_name='stokbarangjadi',
            constraint=models.UniqueConstraint(fields=('entitas', 'grup_bahan', 'item', 'kemasan'), name='uq_stok_jadi_unik'),
        ),
        migrations.AddConstraint(
            model_name='stokbarangjadi',
            constraint=models.CheckConstraint(condition=models.Q(('qty_unit__gte', 0)), name='ck_stok_jadi_unit_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='stokbarangjadi',
            constraint=models.CheckConstraint(condition=models.Q(('qty_kg__gte', 0)), name='ck_stok_jadi_kg_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='stokitemspabrik',
            constraint=models.UniqueConstraint(fields=('entitas', 'grup_bahan', 'item'), name='uq_stok_pabrik_unik'),
        ),
        migrations.AddConstraint(
            model_name='stokitemspabrik',
            constraint=models.CheckConstraint(condition=models.Q(('qty_kg__gte', 0)), name='ck_stok_pabrik_kg_non_negatif'),
        ),
    ]
