# Generated by Django 5.2.10 on 2026-09-19 08:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cabangtoko'),
        ('inventory', '0004_auto_20260913_1742'),
        ('master', '0003_seed_master_produk'),
    ]

    operations = [
        migrations.AddField(
            model_name='stokbarangjadi',
            name='nilai',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Nilai persediaan, akumulasi dari Packing.cost_nom. Bukan harga jual.', max_digits=20),
        ),
        migrations.AddConstraint(
            model_name='stokbarangjadi',
            constraint=models.CheckConstraint(condition=models.Q(('nilai__gte', 0)), name='ck_stok_jadi_nilai_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='stokbarangjadi',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('qty_unit', 0), _negated=True), ('nilai', 0), _connector='OR'), name='ck_stok_jadi_kosong_tanpa_nilai'),
        ),
    ]
