# Generated by Django 5.2.17 on 2026-09-22 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stokbarangjadi_nilai_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packing',
            old_name='kemasan',
            new_name='kemasan_primer',
        ),
        migrations.RenameField(
            model_name='packing',
            old_name='kemasan_dalam',
            new_name='kemasan_sekunder',
        ),
        migrations.RenameField(
            model_name='packing',
            old_name='qty_kemasan_dalam',
            new_name='qty_kemasan_sekunder',
        ),
        migrations.AlterField(
            model_name='packing',
            name='kemasan_primer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing_primer', to='inventory.poolkemasan'),
        ),
        migrations.AlterField(
            model_name='packing',
            name='kemasan_sekunder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packing_sekunder', to='inventory.poolkemasan'),
        ),
        migrations.AlterField(
            model_name='packing',
            name='qty_kemasan_sekunder',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
