# Generated by Django 5.2.17 on 2026-09-22 01:25

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_grupbahan_boleh_dijual_retail'),
        ('inventory', '0006_rename_packing_kemasan'),
        ('master', '0004_hargajual'),
        ('produksi', '0002_tangki_saldo_kg_tangki_saldo_nilai'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kemasan',
            options={'ordering': ['nama'], 'verbose_name': 'Kemasan', 'verbose_name_plural': 'Kemasan'},
        ),
        migrations.AlterModelOptions(
            name='packing',
            options={'ordering': ['-waktu', '-id'], 'verbose_name': 'Packing', 'verbose_name_plural': 'Packing'},
        ),
        migrations.AlterModelOptions(
            name='pembelian',
            options={'ordering': ['-waktu', '-id'], 'verbose_name': 'Pembelian', 'verbose_name_plural': 'Pembelian'},
        ),
        migrations.AlterModelOptions(
            name='poolkemasan',
            options={'ordering': ['kategori', 'produk'], 'verbose_name': 'Pool Kemasan', 'verbose_name_plural': 'Pool Kemasan'},
        ),
        migrations.AlterModelOptions(
            name='poolresource',
            options={'ordering': ['produk'], 'verbose_name': 'Pool Resource', 'verbose_name_plural': 'Pool Resources'},
        ),
        migrations.AlterModelOptions(
            name='saldoentitas',
            options={'verbose_name': 'Saldo entitas', 'verbose_name_plural': 'Saldo entitas'},
        ),
        migrations.AlterModelOptions(
            name='stokbarangjadi',
            options={'verbose_name': 'Stok Barang Jadi', 'verbose_name_plural': 'Stok Barang Jadi'},
        ),
        migrations.AlterModelOptions(
            name='stokitemspabrik',
            options={'verbose_name': 'Stok Items Pabrik', 'verbose_name_plural': 'Stok Items Pabrik'},
        ),
        migrations.RemoveIndex(
            model_name='packing',
            name='ix_pack_batch_baru',
        ),
        migrations.RemoveIndex(
            model_name='packing',
            name='ix_pack_hasil_baru',
        ),
        migrations.AddField(
            model_name='packing',
            name='nilai_kemasan_primer',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
        migrations.AddField(
            model_name='packing',
            name='nilai_kemasan_sekunder',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
        migrations.AddField(
            model_name='packing',
            name='voided_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='pembelian',
            name='harga_per_unit',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='pembelian',
            name='kategori_kemasan',
            field=models.CharField(blank=True, choices=[('PRIMER', 'Primer'), ('SEKUNDER', 'Sekunder'), ('PRIMER_SEKUNDER', 'Primer & Sekunder')], db_index=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pembelian',
            name='qty_unit',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='poolkemasan',
            name='kategori',
            field=models.CharField(choices=[('PRIMER', 'Primer'), ('SEKUNDER', 'Sekunder'), ('PRIMER_SEKUNDER', 'Primer & Sekunder')], db_index=True, default='PRIMER', max_length=20),
        ),
        migrations.AlterField(
            model_name='packing',
            name='posted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='packing',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Diposting'), ('VOID', 'Dibatalkan')], db_index=True, default='DRAFT', max_length=10),
        ),
        migrations.AlterField(
            model_name='packing',
            name='total_unit',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddIndex(
            model_name='packing',
            index=models.Index(fields=['batch', 'status'], name='ix_pack_batch_baru'),
        ),
        migrations.AddIndex(
            model_name='packing',
            index=models.Index(fields=['nama_hasil', 'status'], name='ix_pack_hasil_baru'),
        ),
        migrations.AddConstraint(
            model_name='packing',
            constraint=models.CheckConstraint(condition=models.Q(('nilai_kemasan_primer__gte', 0)), name='ck_pack_nilai_primer_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='packing',
            constraint=models.CheckConstraint(condition=models.Q(('nilai_kemasan_sekunder__gte', 0)), name='ck_pack_nilai_sekunder_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='packing',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('posted_at__isnull', True), ('status', 'DRAFT'), ('voided_at__isnull', True)), models.Q(('posted_at__isnull', False), ('status', 'POSTED'), ('voided_at__isnull', True)), models.Q(('posted_at__isnull', False), ('status', 'VOID'), ('voided_at__isnull', False)), _connector='OR'), name='ck_pack_status_konsisten'),
        ),
        migrations.AddConstraint(
            model_name='packing',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kemasan_sekunder__isnull', True), ('qty_kemasan_sekunder', 0)), models.Q(('kemasan_sekunder__isnull', False), ('qty_kemasan_sekunder__gt', 0)), _connector='OR'), name='ck_pack_sekunder_konsisten'),
        ),
    ]
